[package]
name = "pf-bindings-ruby"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
pf-bindings-core = { path = "../pf-bindings-core" }

[build-dependencies]
cbindgen = "0.24"
