name: pf_bindings
description: Dart bindings for Probably Fair core library
version: 0.1.1
homepage: https://github.com/probablyfair/pf-bindings

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        pluginClass: PfBindingsPlugin
        dartPluginClass: PfBindingsPlugin
      ios:
        pluginClass: PfBindingsPlugin
        dartPluginClass: PfBindingsPlugin
      linux:
        pluginClass: PfBindingsPlugin
        dartPluginClass: PfBindingsPlugin
      macos:
        pluginClass: PfBindingsPlugin
        dartPluginClass: PfBindingsPlugin
      windows:
        pluginClass: PfBindingsPlugin
        dartPluginClass: PfBindingsPlugin
